### ISSUE TITLE
Sugiro fazer alteração na aba "Contatos"

### ISSUE THREAD

**Issue by LacorteGabriel1987** [LucasDevRJ/meu-cafe#1]
Na Section >label >Assunto acredito que type ficou duplicado e igual ao type do email.

Neste caso, deveria usar o type text. Quando fui usar a aba ele esta com formatação errada.

<section class="conteudo-contato" id="contato">
                
## Como está  ##
                    <label class="formulario-texto" for="assunto">Assunto</label>
                  <input class="formulario-entrada" type= "email  id="assunto" required>
            </section>

## Como sugeria estar ##

                  <label class="formulario-texto" for="assunto">Assunto</label>
                   <input class="formulario-entrada" type="text" id="assunto" required>

**Comment by LucasDevRJ** [comment]
Verdade! Irei consertar. Muito obrigado!
