### ISSUE TITLE
Uma sugestão para button Enviar mensagem

### ISSUE THREAD

**Issue by LacorteGabriel1987** [LucasDevRJ/meu-cafe#2]
Trabalho muito bacana e limpo toda estrutura. 

Abaixo no Button "Enviar Mensagem" eu colocaria ele centralizado junto aos blocos acima (Nome, e-mail, assunto, Mensagem), ficaria esteticamente mais alinhado.

## Na seção Section##

                  <input class="formulario-botao" type="submit" value="Enviar Mensagem">

**Comment by LucasDevRJ** [comment]
Obrigado pelo conselho!
